apiversion: apps/v1
kind: Deployment
metadata:
  name: guvi-react-app2-deployment
  labels:
    app: guvi-app2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guvi-app2
  template:
    metadata:
      labels:
        app: guvi-app2
    spec:
      containers:
      - name: guvi-react-app2-container
        image: vikram140602/trend-app
        ports:
        - containerPort: 80

---

apiversion: v1 
kind: Service
metadata:
  name: guvi-react-app2-service
  selector:
    app: guvi-app2
  spec:
    type: LoadBalancer
    selector: 
      app: guvi-app2            # must match labels in Deployment’s podTemplate
  ports:
   - protocol: TCP
     port: 80                   # external LB port (e.g. http port)
     targetPort: 80             # matches containerPort in Deployment
